[tool.black]
line-length = 99
target_version = ['py310']
include = '\.pyi?$'
exclude = '(\.mypy_cache)'

[tool.isort]
line_length = 99
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = "True"
default_section = "THIRDPARTY"
known_first_party = "tentaclio-gdrive"
sections = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
